# Set colorscheme

# Width of a tab
set-option global tabstop 4

# Indent with 4 spaces
set-option global indentwidth 0

# Always keep one line and three columns displayed around the cursor
set-option global scrolloff 1,3

# Display the status bar on top
set-option global ui_options ncurses_status_on_top=true

# Display line numbers
add-highlighter global/ number-lines -hlcursor

# Highlight trailing whitespace
add-highlighter global/ regex \h+$ 0:Error

# Highlight matcing brackets
add-highlighter global/ show-matching

# Softwrap long lines
add-highlighter global/ wrap -word -indent

# Clipboard management mappings
map -docstring "yank the selection into the clipboard" global user y "<a-|> xsel -i<ret>"
map -docstring "paste the clipboard" global user p "<a-!> xsel<ret>"

# Shortcut to quickly exit the editor# ????
#
map global insert <a-i> <esc>

# Color scheme changes
# push:<old mode>:<new mode>
colorscheme tomorrow-night
hook global ModeChange push:normal:insert "colorscheme gruvbox-dark"
hook global ModeChange pop:insert:normal "colorscheme tomorrow-night"
